# Generated by Django 3.0.4 on 2020-03-30 16:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rows', models.IntegerField(default=0)),
                ('cols', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('col', models.IntegerField()),
                ('val', models.IntegerField()),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tron_app.Matrix')),
            ],
        ),
    ]
