# Generated by Django 3.0.4 on 2020-05-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tron_app', '0003_matrix_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrix',
            name='bot_front_view_size',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='matrix',
            name='bot_side_view_size',
            field=models.IntegerField(default=2),
        ),
    ]
